<ChatScreen>:
    canvas:
        Color:
            rgb: utils.get_color_from_hex("#4BFF78")
        Rectangle:
            size: self.size
            pos: self.pos

    TextInput:
        id: message
        hint_text: "Send a Message"
        size_hint: .8, .1
        pos_hint: {"center_x": 0.5, "top": 0.59}
        multiline: False

    ImageButton: # chat button
        source: "icons/Sending.png"
        on_release:
            app.sendMessage()
